### ISSUE TITLE
Weekly pattern

### ISSUE THREAD

**Issue by Vendo232** [cs4alhaider/teams-status-bot#1]
Hello Sir

Great work! 

Question: how would you run this script Mo through Friday , 8am -5pm only?

Thank you

**Comment by cs4alhaider** [comment]
You need to automate running the script from your computer it self

[Here is some example](https://stackoverflow.com/questions/36854193/scheduling-a-terminal-command-or-script-file-to-run-daily-at-a-specific-time-mac)
